# **`Import Libraries `**

In [1]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# import the data

In [10]:
data=pd.read_csv('/content/spam/SPAM text message 20170820 - Data.csv')
data.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

# undersatnding data

In [41]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  5572 non-null   object
 1   Message   5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB

In [42]:
data.shape

(5572, 2)

# missing data

In [43]:
data.isna().sum()

Category    0
Message     0
dtype: int64

# duplicated data

In [44]:
data.duplicated().sum()

np.int64(415)

In [46]:
df=data.drop_duplicates(keep='first')

In [47]:
df.shape

(5157, 2)

In [48]:
x=df.drop(columns=['Category'])
y=df['Category']

In [49]:
y.shape

(5157,)

In [50]:
x.shape

(5157, 1)

In [55]:
x_train.shape

(4125, 1)

In [54]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [56]:
y_train.shape

(4125,)

In [19]:
DecisionTreemodel=DecisionTreeClassifier()

In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline

In [20]:
tfdf=TfidfVectorizer()

In [25]:
piplinetreeDeceion=Pipeline([('tfdf',TfidfVectorizer()),('clf',DecisionTreemodel)])

In [58]:
piplinetreeDeceion.fit(x_train['Message'],y_train)

Pipeline(steps=[('tfdf', TfidfVectorizer()), ('clf', DecisionTreeClassifier())])

In [62]:
y_predections=piplinetreeDeceion.predict(x_test['Message'])

In [63]:
y_predections

array(['ham', 'ham', 'ham', ..., 'ham', 'ham', 'ham'], dtype=object)

In [65]:
dcsntree_acuracy=accuracy_score(y_predections,y_test)
dcsntree_acuracy

0.9622093023255814